import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.39.3';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface EmailRequest {
  to: string;
  template: string;
  data: Record<string, any>;
  userId?: string;
  testMode?: boolean;
}

interface Template {
  id: string;
  template_name: string;
  subject_template: string;
  html_template: string;
  text_template?: string;
  data_schema: Record<string, any>;
}

/**
 * Substitute {{variables}} in template with actual data
 */
function substituteVariables(template: string, data: Record<string, any>): string {
  let result = template;

  // Handle special {{itemsTable}} variable for order confirmations
  if (template.includes('{{itemsTable}}') && data.items && Array.isArray(data.items)) {
    const itemsHtml = `
<table class="items-table">
  <thead>
    <tr>
      <th>Item</th>
      <th>Quantity</th>
      <th>Price</th>
    </tr>
  </thead>
  <tbody>
    ${data.items.map((item: any) => `
    <tr>
      <td>${escapeHtml(item.name)}</td>
      <td>${item.quantity}</td>
      <td>${formatCurrency(item.price, data.currency || 'usd')}</td>
    </tr>
    `).join('')}
  </tbody>
</table>
    `.trim();

    result = result.replace('{{itemsTable}}', itemsHtml);
  }

  // Replace all {{variableName}} with actual values
  for (const [key, value] of Object.entries(data)) {
    const pattern = new RegExp(`{{${key}}}`, 'g');

    // Format special types
    let formattedValue = value;
    if (key === 'subtotal' || key === 'total' || key === 'planPrice') {
      formattedValue = formatCurrency(value as number, data.currency || 'usd');
    } else if (typeof value === 'string') {
      formattedValue = escapeHtml(value);
    } else if (value === null || value === undefined) {
      formattedValue = '';
    } else if (typeof value === 'object') {
      // Skip complex objects (like items array)
      continue;
    }

    result = result.replace(pattern, String(formattedValue));
  }

  // Replace unsubscribe/preferences URLs (these should be generated by the system)
  result = result.replace(/{{unsubscribeUrl}}/g, `https://drinklonglife.com/unsubscribe?token={{unsubscribe_token}}`);
  result = result.replace(/{{preferencesUrl}}/g, `https://drinklonglife.com/account/email-preferences`);

  return result;
}

/**
 * Format currency amount (cents to dollar display)
 */
function formatCurrency(amount: number, currency: string): string {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: currency.toUpperCase(),
  }).format(amount / 100);
}

/**
 * Escape HTML to prevent XSS
 */
function escapeHtml(text: string): string {
  const map: Record<string, string> = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#039;',
  };
  return text.replace(/[&<>"']/g, (m) => map[m]);
}

/**
 * Check user email preferences
 */
async function checkEmailPreferences(
  supabase: any,
  userId: string | undefined,
  templateName: string
): Promise<{ allowed: boolean; token?: string }> {
  if (!userId) {
    return { allowed: true }; // No user ID, allow (e.g., guest checkout)
  }

  const { data: prefs, error } = await supabase
    .from('email_preferences')
    .select('*')
    .eq('user_id', userId)
    .single();

  if (error || !prefs) {
    // No preferences found, allow by default
    return { allowed: true };
  }

  // Check global email setting
  if (!prefs.all_emails_enabled) {
    return { allowed: false };
  }

  // Check category-specific settings
  const categoryMap: Record<string, string> = {
    order_confirmation: 'order_confirmations',
    subscription_confirmation: 'subscription_notifications',
    newsletter_welcome: 'newsletter',
    contact_form_notification: 'transactional_emails',
  };

  const prefKey = categoryMap[templateName];
  if (prefKey && prefs[prefKey] === false) {
    return { allowed: false };
  }

  return { allowed: true, token: prefs.unsubscribe_token };
}

serve(async (req) => {
  // Handle CORS preflight
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const resendApiKey = Deno.env.get('RESEND_API_KEY')!;
    const emailFrom = Deno.env.get('EMAIL_FROM') || 'Long Life <hello@drinklonglife.com>';

    if (!resendApiKey) {
      throw new Error('RESEND_API_KEY not configured');
    }

    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    // Parse request body
    const { to, template: templateName, data, userId, testMode }: EmailRequest = await req.json();

    if (!to || !templateName || !data) {
      return new Response(
        JSON.stringify({ error: 'Missing required fields: to, template, data' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // 1. Load published template from database
    const { data: template, error: templateError } = await supabase
      .from('email_template_versions')
      .select('*')
      .eq('template_name', templateName)
      .eq('version_type', 'published')
      .single() as { data: Template | null; error: any };

    if (templateError || !template) {
      console.error('Template not found:', templateName, templateError);
      return new Response(
        JSON.stringify({ error: `Template '${templateName}' not found` }),
        { status: 404, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // 2. Check user email preferences (skip if test mode)
    if (!testMode) {
      const { allowed } = await checkEmailPreferences(supabase, userId, templateName);
      if (!allowed) {
        console.log(`Email not sent to ${to}: User has disabled ${templateName} emails`);
        return new Response(
          JSON.stringify({ success: false, reason: 'User email preferences' }),
          { status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        );
      }
    }

    // 3. Substitute variables in subject and HTML
    let subject = substituteVariables(template.subject_template, data);
    let htmlContent = substituteVariables(template.html_template, data);

    // Add [TEST] prefix in test mode
    if (testMode) {
      subject = `[TEST] ${subject}`;
    }

    // 4. Create audit record in email_notifications
    const { data: notification, error: notificationError } = await supabase
      .from('email_notifications')
      .insert({
        user_id: userId || null,
        email: to,
        template_name: templateName,
        subject,
        html_content: htmlContent,
        template_data: data,
        status: 'pending',
        is_test: testMode || false,
      })
      .select()
      .single();

    if (notificationError) {
      console.error('Failed to create notification record:', notificationError);
      throw new Error('Failed to create audit record');
    }

    // 5. Send email via Resend API
    const resendResponse = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${resendApiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        from: emailFrom,
        to: [to],
        subject,
        html: htmlContent,
        headers: {
          'X-Notification-ID': notification.id,
        },
      }),
    });

    const resendData = await resendResponse.json();

    if (!resendResponse.ok) {
      console.error('Resend API error:', resendData);

      // Update notification with error
      await supabase
        .from('email_notifications')
        .update({
          status: 'failed',
          error_message: JSON.stringify(resendData),
        })
        .eq('id', notification.id);

      throw new Error(`Failed to send email: ${JSON.stringify(resendData)}`);
    }

    // 6. Update notification as sent
    await supabase
      .from('email_notifications')
      .update({
        status: 'sent',
        sent_at: new Date().toISOString(),
        metadata: { resend_id: resendData.id },
      })
      .eq('id', notification.id);

    console.log(`✅ Email sent: ${templateName} to ${to} (Resend ID: ${resendData.id})`);

    return new Response(
      JSON.stringify({
        success: true,
        id: resendData.id,
        notificationId: notification.id,
      }),
      { status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error) {
    console.error('Send email error:', error);
    return new Response(
      JSON.stringify({
        error: error instanceof Error ? error.message : 'Unknown error',
      }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
